apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HannaJyha/webapp-helm.git 
    targetRevision: HEAD
    path: ./webapp-chart
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: app 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true