apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "webapp.name" . }}
    helm.sh/chart: {{ include "webapp.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "webapp.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "webapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
      - name: nginx-config-volume
        configMap:
          name: {{ .Values.nginxConfig.name }}
      containers:
      - name: app-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        resources:
          {{- toYaml .Values.resources.app | nindent 10 }}
        env:
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.appSecret.name }}
              key: {{ .Values.appSecret.key }}
      
      - name: nginx-proxy
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        resources:
          {{- toYaml .Values.resources.nginx | nindent 10 }}
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.appSecret.key }}: {{ .Values.appSecret.valueBase64 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginxConfig.name }}
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
{{ .Values.nginxConfig.config | indent 4 }}